# Global logging configuration
logging:
  level: "debug"   # Options: debug, info, warn, error
  format: "json"   # Options: text, json

server:
  listenParams:
    - address: ":8095"
      protocol: "https"
      tls:
        enabled: true
        cert_file: "../../build/certs/server.crt"
        key_file: "../../build/certs/server.key"
        min_version: "1.2"

pipelines:
  - id: observability-demo
    agentId: "*"
    protocol: http
    nodes:
      - id: start
        type: egress
        config:
          upstream_url: "https://httpbin.org/anything"
        on:
          success: ""
