logging:
  level: debug
  pretty: true

telemetry:
  otlp_endpoint: "" # Set this if you have a local collector
  insecure: true

server:
  admin_address: ":19090"
  data_address: ":8090"

  # TLS configuration
  tls:
    enabled: true
    cert_file: "../../../../build/certs/server.crt"
    key_file: "../../../../build/certs/server.key"
    min_version: "1.2"
